# Generated by Django 5.2.4 on 2025-07-10 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fraudflag",
            options={},
        ),
        migrations.AlterField(
            model_name="fraudflag",
            name="reason",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="amount_requested",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="date_applied",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("flagged", "Flagged"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="fraudflag",
            index=models.Index(
                fields=["loan_application", "created_at"],
                name="loans_fraud_loan_ap_6e4bfb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fraudflag",
            index=models.Index(
                fields=["reason", "created_at"], name="loans_fraud_reason_41d0ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudflag",
            index=models.Index(
                fields=["loan_application", "reason"],
                name="loans_fraud_loan_ap_431c2d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loanapplication",
            index=models.Index(
                fields=["user", "status"], name="loans_loana_user_id_5266b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanapplication",
            index=models.Index(
                fields=["user", "date_applied"], name="loans_loana_user_id_5b544b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanapplication",
            index=models.Index(
                fields=["status", "date_applied"], name="loans_loana_status_d0e6bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanapplication",
            index=models.Index(
                fields=["amount_requested", "status"],
                name="loans_loana_amount__4bd9d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loanapplication",
            index=models.Index(
                fields=["date_applied", "status"], name="loans_loana_date_ap_d30180_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanapplication",
            index=models.Index(
                fields=["user", "status", "date_applied"],
                name="loans_loana_user_id_536ec9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loanapplication",
            index=models.Index(
                fields=["status", "amount_requested", "date_applied"],
                name="loans_loana_status_963d9e_idx",
            ),
        ),
    ]
